### ISSUE TITLE
identify the object that caused the package.xml not to be generated

### ISSUE THREAD

**Issue by elitrGit** [scolladon/sfdc-git-package#10] opened 2018-11-08 08:30 UTC
Hi,
I encounter the following issue:
One of the build failed on:

(node:13526) UnhandledPromiseRejectionWarning: Unhandled Promise Rejection (rejection id: 2): Error Unexpected close tag Line 35581 Column 15 Char: >

(node:13256): [DEP0018] DeprecationWarning: Unhandled Promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The solution was  running the sgp command on each folder (that contain the objects) ,until we found the directory that contain the failed object .Then  inside the directory run the sgp until we found the object that cause the failure
Is it possible that the sgp command will print the file that cause the failure ?
regards

**Comment by scolladon** [comment] 2018-11-09 09:00
@elitrGit are you sure the issue is in this module ?
Is is related to [sfdc-generate-package](https://github.com/scolladon/sfdc-generate-package) instead ?

**Comment by elitrGit** [comment] 2018-11-11 08:51
sorry - my mistake. wrong module.. can you move this issue to sfdc-generate-package?

**Comment by scolladon** [comment] 2018-11-12 09:01
I do not know how to do it.

I'm closing this one. 

Please recreate it in the right repository :)

**Closed as completed** 2018-11-12 09:01 UTC

**Comment by elitrGit** [comment] 2018-11-12 09:46
done
